apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: surfersweb
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: surferslookout
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/language: python
spec:
  params:
  - name: clusterBuilder
    value: full
  - name: annotations
    value:
      autoscaling.knative.dev/min-scale: "1"
      autoscaling.knative.dev/max-scale: "50"
      autoscaling.knative.dev/scale-down-delay: "2s"
      autoscaling.knative.dev/initial-scale: "1"
      autoscaling.knative.dev/window: "10s"
      autoscaling.knative.dev/target: "40"
      autoscaling.knative.dev/metric: "rps"
      autoscaling.knative.dev/target: "60"
  source:
    git:
      url: https://github.com/davlloyd/surfers-web
      ref:
        branch: main
  serviceClaims:
    - name: db
      ref:
        apiVersion: v1
        kind: Secret
        name: surferslookout-db
    - name: api
      ref:
        apiVersion: v1
        kind: Secret
        name: surfersweb-api
  env:
  - name: GOOGLE_API_KEY
    value: yourapikey

    